id: "@1337TR/better-taskbar"
metadata:
  displayName: Better taskbar
  author: 1337TR
  description: Make the taskbar better, adding smoothing, focus app indicator.
  tags: ['weg']
styles:
  weg: |

    .weg-item {
      transition: all 0.2s ease;
    }
    .weg-item-icon:hover {
      transform: scale(0.95);
    }
    .weg-item-icon:active {
      transform: scale(0.85);
      transition: transform 0.2s ease;
    }
    .weg-item:has(.weg-item-open-sign-focused) {
      transform: scale(1.1);
    }