metadata:
  displayName: Kay Mini
  author: IriKay
  description: Edit of Tech-Mini (ScaDane), Centering, Tray, Focus (FunTust) 
  tags: ['toolbar']
  
styles:
  toolbar: |
    .ft-bar-bg-layer-1 {
      display: none;
    }

    .ft-bar-bg-layer-2 {
      opacity: 0.6;
    }  

    .ft-bar {
        width: 59% !important;
        left: 50%;
        margin-right: -50%;
        bottom: -0.37em;
        transform: translate(-50%);
        transform-style: preserve-3d;

        .bg-layer-2{
          border: 1px solid rgba(255, 255, 255, 0.8);
          border-bottom-left-radius: 11px;
          border-bottom-right-radius: 11px;
          border-top-left-radius: 11px;
          border-top-right-radius: 11px;       
        }
    }

    .ft-bar-item {
      opacity: 0.8;

    &.ft-bar-item-clickable {
      opacity: 0.9;
      margin: 6px;
      padding: 3px;
      border-radius: 5px;
      height: 20px;

    &:hover {
      border: 1px solid rgb(255, 255, 255, 0.5);
        }
      }
    }

    .calendar-container {
    margin: var(--popups-margin);
    width: 350px;
    padding: 4px;
    transition-duration: 300ms;

    .bg-layer-1 {
      background-color: rgba(20, 20, 20, 0.7);
      border: 1px solid rgba(255, 255, 255, 0.5);
      border-radius: 11px;}
      }

    .tray {
    margin: var(--popups-margin);
    left: 27px;

    .tray-bg-layer-1 {
      background-color: rgba(20, 20, 20, 0.6);
      border: 1px solid rgba(255, 255, 255, 0.5);
      border-radius: 11px;
      }
    }

    .tray-list {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(32px, 1fr));
      padding: 6px;
    }

    .tray-item {
      display: flex;
      justify-content: center;
      align-items: center;
      padding: 6px;
    }
    
    .tray-item-label {
      display: none !important;
    }

    .tray-item-icon-container {
      width: 16px;
      height: 16px;
    }    

    .media-control {
    margin: var(--popups-margin);
    width: 250px;
    padding: 10px;
    right: 12px;

    .bg-layer-1 {
      background-color: rgba(20, 20, 20, 0.6);
      border: 1px solid rgba(255, 255, 255, 0.5);
      border-radius: 11px;
      }
    }

    .notifications {
    margin: var(--popups-margin);
    width: 350px;
    height: 300px;
    padding: 10px;
    display: flex;
    flex-direction: column;
    gap: 10px;
    max-height: 450px;
    right: 102px;

    .bg-layer-1 {
      border: 1px solid rgba(255, 255, 255, 0.5);
      opacity: 0;
      background-size: cover;
      border-radius: 11px;
    }

    .bg-layer-2 {
      opacity: 0.90;
      background-color: rgba(20, 20, 20, 0.6);
      border: 1px solid rgba(255, 255, 255, 0.5);
      border-radius: 11px;
      }
    }

    .fast-settings {
    padding: 12px 16px;
    margin: var(--popups-margin);
    right: 118px;

    .fast-settings-bg-layer-1 {
      background-color: rgba(20, 20, 20, 0.6);
      border: 1px solid rgba(255, 255, 255, 0.5);
      border-radius: 11px;
      }
    }

  weg: |
    .taskbar-bg-layer-2 {
      opacity: 0.5;
      background-color: rgba(20, 20, 20, 0.8);
      border: 1px solid rgba(255, 255, 255, 0.5);
      border-radius: 15px;
    }

    .taskbar .weg-item:has(.weg-item-open-sign-focused) {
      .e {
        background-color: #434547;
        border-radius: 25%;
      }
    }