info:
  displayName: Tech Minimalism
  author: ScaDane
  description: Tech Minimalism theme
  tags: ['weg', 'launcher', 'toolbar']
layers:
  weg:
    bg: 2
  toolbar:
    bg: 1
styles:
  weg: |
    .taskbar-bg-layer-1 {
    opacity: 0.0;
    filter: saturate(0);
    background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 250 250' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='10' numOctaves='3' stitchTiles='stitch '/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E");
    background-size: cover;
    border-radius: 20px;}

    .taskbar-bg-layer-2 {
      opacity: 0.5;
      background-color: rgb(0, 0, 0, 0.5);
      border-radius: 15px;}

    .weg-item-preview-container {
    padding: 10px;
    border-radius: 10px;

    .preview-bg-layer-1 {
      background-color: rgb(20, 20, 20, 0.7);
      border-radius: 10px;
    }}



    .weg-item {
    .bg-layer-1 {
      //background-color: rgb(20, 20, 20, 0.9);
      border-radius: 25%;
      //box-shadow: 0px 2px 3px 0px rgba(0, 0, 0, 0.5);
    }
    &.media-session-container {
    &.media-session-container-horizontal {
      transition-duration: 300ms;
      width: calc(var(--config-item-size) * 0.6 + var(--config-space-between-items) * 2);
      &:hover {
        width: calc(var(--config-item-size) * 2.8 + var(--config-space-between-items) * 2); 
    }
    }
    &.media-session-container-vertical {
      height: calc(var(--config-item-size) * 3 + var(--config-space-between-items) * 2);
    }
    }
    
    
    
    }

    .weg-context-menu-container {
    padding: 3px;

    .menu-bg-layer-1 {
      background-color: rgb(20, 20, 20, 0.85);
      border-radius: 10px;
    }



  toolbar: |
    .ft-bar-bg-layer-1 {
      display: none;
    }

    .ft-bar-bg-layer-2 {
      display: none;
    }

    .ft-bar-item {
      background-color: rgba(40, 40, 40, 0.7);
      border-radius: 11px;
      padding: 2px 8px;
      height: 25px;
      //transition: background-color 400ms ease-in-out;
      transition-duration: 20ms;
      border: 2px solid var(--config-accent-light-color);

      &.ft-bar-item-clickable {
        transition-duration: 300ms;
        padding: 2px 8px;
        border-radius: 11px;

        &:hover {
          transition-duration: 300ms;
          background-color: rgba(50, 50, 50, 1);
          border: 2px solid rgb(255, 255, 255);

        }
      }
    }


    .calendar-container {
    margin: var(--popups-margin);
    width: 250px;
    padding: 1px;
    transition-duration: 300ms;

    .bg-layer-1 {
      background-color: rgba(20, 20, 20, 0.7);
      border: 2px solid rgba(255, 255, 255, 0.8);
      border-radius: 12px;}}
    
    .tray {
    margin: var(--popups-margin);

    .tray-bg-layer-1 {
      background-color: rgba(20, 20, 20, 0.7);
      border-radius: 15px;
      box-shadow: 0 0 10px 10px #0001;
      border: 2px solid rgba(255, 255, 255, 0.8);
    }}



    .wlan-selector {
    margin: var(--popups-margin);
    width: 260px;
    box-shadow: 0 0 10px 10px #0001;
    display: flex;
    flex-direction: column;

    .wlan-selector-bg-layer-1 {

      border: 2px solid rgba(255, 255, 255, 0.8);
      background-color: rgba(20, 20, 20, 0.7);
      border-radius: 15px;}}

    .media-control {
    margin: var(--popups-margin);
    width: 300px;
    padding: 10px;

    .bg-layer-1 {
      border: 2px solid rgba(255, 255, 255, 0.8);
      background-color: rgba(20, 20, 20, 0.7);
      border-radius: 15px;
    }
    }
    .fast-settings {
    padding: 12px 16px;
    margin: var(--popups-margin);

    .fast-settings-bg-layer-1 {
      border: 2px solid rgba(255, 255, 255, 0.8);
      background-color: rgba(20, 20, 20, 0.7);
      border-radius: 15px;
    }
    }
    .notifications {
    margin: var(--popups-margin);
    width: 350px;
    height: 300px;
    padding: 10px;
    display: flex;
    flex-direction: column;
    gap: 10px;
    max-height: 450px;

    .bg-layer-1 {
      border: 2px solid rgba(255, 255, 255, 0.8);
      opacity: 0.1;
      filter: saturate(0);
      background-size: cover;
      border-radius: 12px;
    }

    .bg-layer-2 {
      opacity: 0.90;
      border: 2px solid rgba(255, 255, 255, 0.8);
      background-color: rgba(20, 20, 20, 0.7);
      border-radius: 20px;
    }
    }



    
    .ft-bar-item-context-menu-container,
    .tb-context-menu-container {
      min-width: 160px;

      .bg-layer-1 {
        background-color: rgba(20, 20, 20, 0.8);
        border-radius: 10px;
      }
    }
    .userhome {
    margin: var(--popups-margin);
    width: 300px;
    box-shadow: 0 0 10px 10px #0001;
    display: flex;
    flex-direction: column;
    padding: 10px;
    max-height: calc(99vh - var(--config-height));

    .userhome-bg-layer-1 {
      background-color: rgba(20, 20, 20, 0.8);
      border: 2px solid rgba(255, 255, 255, 0.8);
      border-radius: 15px;
    }
    }
    .userhome-power {
    z-index: 1;
    display: flex;
    gap: 6px;
    align-items: center;
    flex-wrap: wrap;
    margin-top: 1em;;

    > .userhome-power-label {
      display: block;

      width: 100%;
      flex-basis: 100%;
    }
    > .userhome-power-button {
      position: relative;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 8px 12px;
      flex: 1;
      border: 0;
      border-radius: 15px;
      border: 2px solid rgba(255, 255, 255, 0.8);
      transition: background-color 0.4s ease-in-out;
      box-shadow: 0 0 3px 1px rgba(0, 0, 0, 0.4);

      &:hover {
        background-color: var(--color-gray-200);
        border: 2px solid var(--config-accent-light-color);
      }
    }
    }






  launcher: |
    .launcher {
    --padding: 15px;
    width: 100%;
    height: 90%;
    background-color: rgba(20, 20, 20, 0.7);
    border-radius: 20px;
    //box-shadow: 0 4px 10px 4px #0001;
    display: center;
    //grid-template-rows: auto 1fr auto;}

